[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm run install-all"]

[phases.build]
cmds = ["cd client && npm run build", "cd server && npm run build"]

[start]
cmd = "cd server && npm start" 